CREATE DATABASE IF NOT EXISTS stockMarket;

USE stockMarket;
 
		
CREATE TABLE IF NOT EXISTS enterprise (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  serialnumber VARCHAR(255) NULL DEFAULT NULL,
  description VARCHAR(255) NULL DEFAULT NULL,
  branches BIGINT(20) NULL DEFAULT NULL,
  countries BIGINT(20) NULL DEFAULT NULL, 
  marketvalue DOUBLE NULL DEFAULT NULL,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;